"""Runs the Phase 1-4 name/email category-pipeline scenarios with readable,
per-turn logging: which phase, which category, and which question is being
answered on each line.

Scenarios live in scripts/scenarios/category_pipeline/ (generated by
scripts/generate_category_pipeline_scenarios.py) and are kept out of the
scripts/scenarios/ regression suite on purpose, so they don't need to be
registered in tests/unit/test_convo_runner_parsing.py.

Requires a running backend, started the same way as scripts/convo_runner.py
(see that module's docstring):
    TRAILERPLACE_PERSIST_CHATS=0 DEBUG_STATE_ENDPOINT=1 \
    CATEGORY_DEFAULTS_JSON='{}' ./.venv/Scripts/python.exe main.py

Usage:
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py                 # everything
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --phase 1       # Phase 1 only
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --category Dump # one category
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --phase 4       # the multi-switch flow

Every run mirrors its console output to a timestamped file under logs/, in
addition to whatever the backend itself writes to logs/YYYY-MM-DD.log for the
same turns.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
import uuid
from pathlib import Path
from typing import Any

import requests

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
SCRIPTS_DIR = ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from convo_runner import _fetch_state, evaluate_assertions, load_scenarios  # noqa: E402

PIPELINE_DIR = SCRIPTS_DIR / "scenarios" / "category_pipeline"
DEFAULT_BASE_URL = "http://127.0.0.1:8000"


class _Tee:
    """Writes to every stream given (console + log file) on each print()."""

    def __init__(self, *streams: Any) -> None:
        self._streams = streams

    def write(self, text: str) -> None:
        for stream in self._streams:
            stream.write(text)
            stream.flush()

    def flush(self) -> None:
        for stream in self._streams:
            stream.flush()


def run_pipeline(base_url: str, scenarios: list[dict[str, Any]], transcript: list | None = None) -> bool:
    """Run every scenario. When `transcript` is given, each turn is appended to it as a
    dict so the caller can write a readable Markdown record of the whole conversation -
    the console log interleaves turns with assertion noise and is awkward to read back.
    """
    all_passed = True
    for scenario in scenarios:
        session_id = str(uuid.uuid4())
        print(f"\n===== [{scenario['name']}] (phase={scenario.get('phase')}, "
              f"category={scenario.get('category')}, session={session_id}) =====")
        turns_record: list[dict[str, Any]] = []
        for turn in scenario.get("turns", []):
            label = turn.get("label", "(no label)")
            user_message = turn.get("user", "")
            response = requests.post(
                f"{base_url}/chat",
                json={"session_id": session_id, "turn_id": str(uuid.uuid4()), "message": user_message},
                timeout=180,
            )
            response.raise_for_status()
            body = response.json()
            reply_text = body.get("assistant_text", "")
            listings = body.get("listings") or []
            state = _fetch_state(base_url, session_id)
            failures = evaluate_assertions(turn, reply_text=reply_text, state=state, listings=listings)
            status = "PASS" if not failures else "FAIL"
            if failures:
                all_passed = False
            print(f"[{status}] {label}")
            print(f"    USER : {user_message}")
            print(f"    REPLY: {reply_text}")
            if listings:
                print(f"    LISTINGS: {len(listings)} returned")
            for failure in failures:
                print(f"    FAILURE: {failure}")
            turns_record.append({
                "label": label, "user": user_message, "reply": reply_text,
                "listings": len(listings), "status": status, "failures": failures,
                "emails_sent": state.get("emails_sent") or [],
                "slots": state.get("slots") or {},
                "features": state.get("non_metadata_features") or [],
            })
        if transcript is not None:
            transcript.append({
                "name": scenario["name"], "phase": scenario.get("phase"),
                "category": scenario.get("category"), "session": session_id,
                "turns": turns_record,
            })
    return all_passed


def write_markdown(transcript: list[dict[str, Any]], path: Path) -> None:
    """A readable record of every conversation, for auditing the replies by eye."""
    total = sum(len(s["turns"]) for s in transcript)
    failed = [s for s in transcript if any(t["failures"] for t in s["turns"])]
    out = [
        "# Category pipeline run",
        "",
        f"- Run at: {dt.datetime.now():%Y-%m-%d %H:%M:%S}",
        f"- Scenarios: {len(transcript)}   turns: {total}",
        f"- Scenarios with at least one failed assertion: {len(failed)}",
        "",
    ]
    if failed:
        out += ["## Scenarios with failures", ""]
        for s in failed:
            bad = [t for t in s["turns"] if t["failures"]]
            out.append(f"- [{s['name']}](#{s['name']}) - {len(bad)} turn(s)")
        out.append("")
    out += ["---", ""]
    for s in transcript:
        mark = "FAIL" if any(t["failures"] for t in s["turns"]) else "PASS"
        out += [f"<a id=\"{s['name']}\"></a>",
                f"## [{mark}] {s['name']}",
                "",
                f"`phase {s['phase']}` · `{s['category']}` · session `{s['session']}`",
                ""]
        for t in s["turns"]:
            out += [f"**{t['status']}** - {t['label']}", "",
                    f"> **User:** {t['user']}", ""]
            reply = (t["reply"] or "").strip() or "(empty reply)"
            out += ["```", reply, "```", ""]
            bits = []
            if t["listings"]:
                bits.append(f"listings: {t['listings']}")
            if t["emails_sent"]:
                bits.append(f"emails: {t['emails_sent']}")
            if t["features"]:
                bits.append(f"features: {t['features']}")
            if bits:
                out += ["<sub>" + " · ".join(bits) + "</sub>", ""]
            for f in t["failures"]:
                out += [f"> FAILURE: {f}", ""]
        out += ["---", ""]
    path.write_text(chr(10).join(out), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--phase", choices=["1", "2", "3", "4", "5", "6"],
                        help="Only run this phase's scenarios (5=email tool calls, 6=axles).")
    parser.add_argument("--category", help="Only run this category's scenarios (e.g. Dump, 'Car Hauler').")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help=f"Backend base URL (default {DEFAULT_BASE_URL}).")
    args = parser.parse_args(argv)

    scenarios = load_scenarios(PIPELINE_DIR)
    if args.phase:
        scenarios = [s for s in scenarios if str(s.get("phase")) == args.phase]
    if args.category:
        scenarios = [s for s in scenarios if args.category.lower() in str(s.get("category", "")).lower()]
    if not scenarios:
        print("No matching scenarios.")
        return 1

    # Run phase-major: every category's Phase 1 first, then every Phase 2, then
    # every Phase 3 (Phase 4's single multi-category scenario runs last).
    scenarios.sort(key=lambda s: (s.get("phase", 0), str(s.get("category", "")), s["name"]))

    logs_dir = ROOT / "logs"
    logs_dir.mkdir(exist_ok=True)
    stamp = f"{dt.datetime.now():%Y%m%d_%H%M%S}"
    log_path = logs_dir / f"category_pipeline_{stamp}.log"
    md_path = logs_dir / f"category_pipeline_{stamp}.md"

    transcript: list[dict[str, Any]] = []
    real_stdout = sys.stdout
    with log_path.open("w", encoding="utf-8") as log_file:
        sys.stdout = _Tee(real_stdout, log_file)
        try:
            print(f"Running {len(scenarios)} scenario(s) against {args.base_url}")
            passed = run_pipeline(args.base_url, scenarios, transcript)
        finally:
            sys.stdout = real_stdout

    write_markdown(transcript, md_path)
    print("")
    print("ALL PASSED" if passed else "SOME FAILED")
    print(f"  console log : {log_path}")
    print(f"  transcript  : {md_path}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
