"""Runs the Phase 1-4 name/email category-pipeline scenarios with readable,
per-turn logging: which phase, which category, and which question is being
answered on each line.

Scenarios live in scripts/scenarios/category_pipeline/ (generated by
scripts/generate_category_pipeline_scenarios.py) and are kept out of the
scripts/scenarios/ regression suite on purpose, so they don't need to be
registered in tests/unit/test_convo_runner_parsing.py.

Requires a running backend, started the same way as scripts/convo_runner.py
(see that module's docstring):
    TRAILERPLACE_PERSIST_CHATS=0 DEBUG_STATE_ENDPOINT=1 \
    CATEGORY_DEFAULTS_JSON='{}' ./.venv/Scripts/python.exe main.py

Usage:
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py                 # everything
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --phase 1       # Phase 1 only
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --category Dump # one category
    ./.venv/Scripts/python.exe scripts/run_category_pipeline.py --phase 4       # the multi-switch flow

Every run mirrors its console output to a timestamped file under logs/, in
addition to whatever the backend itself writes to logs/YYYY-MM-DD.log for the
same turns.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
import uuid
from pathlib import Path
from typing import Any

import requests

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
SCRIPTS_DIR = ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from convo_runner import _fetch_state, evaluate_assertions, load_scenarios  # noqa: E402

PIPELINE_DIR = SCRIPTS_DIR / "scenarios" / "category_pipeline"
DEFAULT_BASE_URL = "http://127.0.0.1:8000"


class _Tee:
    """Writes to every stream given (console + log file) on each print()."""

    def __init__(self, *streams: Any) -> None:
        self._streams = streams

    def write(self, text: str) -> None:
        for stream in self._streams:
            stream.write(text)
            stream.flush()

    def flush(self) -> None:
        for stream in self._streams:
            stream.flush()


def run_pipeline(base_url: str, scenarios: list[dict[str, Any]]) -> bool:
    all_passed = True
    for scenario in scenarios:
        session_id = str(uuid.uuid4())
        print(f"\n===== [{scenario['name']}] (phase={scenario.get('phase')}, "
              f"category={scenario.get('category')}, session={session_id}) =====")
        for turn in scenario.get("turns", []):
            label = turn.get("label", "(no label)")
            user_message = turn.get("user", "")
            response = requests.post(
                f"{base_url}/chat",
                json={"session_id": session_id, "turn_id": str(uuid.uuid4()), "message": user_message},
                timeout=180,
            )
            response.raise_for_status()
            body = response.json()
            reply_text = body.get("assistant_text", "")
            listings = body.get("listings") or []
            state = _fetch_state(base_url, session_id)
            failures = evaluate_assertions(turn, reply_text=reply_text, state=state, listings=listings)
            status = "PASS" if not failures else "FAIL"
            if failures:
                all_passed = False
            print(f"[{status}] {label}")
            print(f"    USER : {user_message}")
            print(f"    REPLY: {reply_text}")
            if listings:
                print(f"    LISTINGS: {len(listings)} returned")
            for failure in failures:
                print(f"    FAILURE: {failure}")
    return all_passed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--phase", choices=["1", "2", "3", "4"], help="Only run this phase's scenarios.")
    parser.add_argument("--category", help="Only run this category's scenarios (e.g. Dump, 'Car Hauler').")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help=f"Backend base URL (default {DEFAULT_BASE_URL}).")
    args = parser.parse_args(argv)

    scenarios = load_scenarios(PIPELINE_DIR)
    if args.phase:
        scenarios = [s for s in scenarios if str(s.get("phase")) == args.phase]
    if args.category:
        scenarios = [s for s in scenarios if args.category.lower() in str(s.get("category", "")).lower()]
    if not scenarios:
        print("No matching scenarios.")
        return 1

    # Run phase-major: every category's Phase 1 first, then every Phase 2, then
    # every Phase 3 (Phase 4's single multi-category scenario runs last).
    scenarios.sort(key=lambda s: (s.get("phase", 0), str(s.get("category", "")), s["name"]))

    logs_dir = ROOT / "logs"
    logs_dir.mkdir(exist_ok=True)
    log_path = logs_dir / f"category_pipeline_{dt.datetime.now():%Y%m%d_%H%M%S}.log"

    real_stdout = sys.stdout
    with log_path.open("w", encoding="utf-8") as log_file:
        sys.stdout = _Tee(real_stdout, log_file)
        try:
            print(f"Running {len(scenarios)} scenario(s) against {args.base_url}")
            passed = run_pipeline(args.base_url, scenarios)
        finally:
            sys.stdout = real_stdout

    print(f"\n{'ALL PASSED' if passed else 'SOME FAILED'} -- log written to {log_path}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
